### ISSUE TITLE
微信满员了，请重新上传新的微信图片 我可以免费做管理员

### ISSUE THREAD

**Issue by ArtificialZeng** [CVI-SZU/Linly#123]
微信满员了，请重新上传新的微信图片

**Comment by michelle-chou25** [comment]
二维码都过期了耶

**Comment by ydli-ai** [comment]
收到
________________________________
发件人: michelle-chou25 ***@***.***>
发送时间: Monday, July 31, 2023 10:45:34 AM
收件人: CVI-SZU/Linly ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [CVI-SZU/Linly] 微信满员了，请重新上传新的微信图片 我可以免费做管理员 (Issue #123)


二维码都过期了耶

―

**Comment by ydli-ai** [comment]
已更新
