### ISSUE TITLE
In 中文指令学习 构建[指令数据集] 并预处理：What are the files and their contents in the $INSTRUCTION_PATH?

### ISSUE THREAD

**Issue by wtwong316** [CVI-SZU/Linly#81]
In 中文指令学习
构建[指令数据集] 并预处理：

What are the files and their contents in the $INSTRUCTION_PATH?
>>python3 preprocess.py --corpus_path $INSTRUCTION_PATH --spm_model_path $LLaMA_PATH/tokenizer.model \
                      --dataset_path $OUTPUT_DATASET_PATH --data_processor alpaca --seq_length 512

I have gone through the wiki and the whole project. I can't find one. Please help. Thanks.

**Comment by ydli-ai** [comment]
这里就是 [指令数据集]  得到的文件路径
