### ISSUE TITLE
33b Huggingface 格式怎么转成TencentPretrain 格式

### ISSUE THREAD

**Issue by lyy-zz** [CVI-SZU/Linly#89]
模型下载章节写着提供脚本，支持格式互转，但实际脚本只有tp转hf，请问hf转tp可以参考哪里？
![image](https://github.com/CVI-SZU/Linly/assets/31911972/76e9a81f-7c57-47f5-9249-2703a0f32961)

**Comment by ydli-ai** [comment]
在tencentpretrain的scripts目录中
________________________________
发件人: lyy-zz ***@***.***>
发送时间: Friday, May 26, 2023 5:34:51 PM
收件人: CVI-SZU/Linly ***@***.***>
抄送: Subscribed ***@***.***>
主题: [CVI-SZU/Linly] 33b Huggingface 格式怎么转成TencentPretrain 格式 (Issue #89)


模型下载章节写着提供脚本，支持格式互转，但实际脚本只有tp转hf，请问hf转tp可以参考哪里？
[image]<https://user-images.githubusercontent.com/31911972/241180733-76e9a81f-7c57-47f5-9249-2703a0f32961.png>

―

**Comment by lyy-zz** [comment]
明白了，感谢回复
